name: Simple Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: |
          echo "Called workflow executed successfully"
          echo "Message: ${{ inputs.message }}"
